(define (problem FGB)
	(:domain FoxGooseBeans)
	(:objects fox goose beans farmer)
	(:init (FOX fox)
	(GOOSE goose)
	(BEANS beans)
	(FARMER farmer)
	(onLeftBank fox)
	(onLeftBank goose)
	(onLeftBank beans)
	(onLeftBank farmer))
	(:goal (and
		(not (onLeftBank fox))
		(not (onLeftBank goose))
		(not (onLeftBank beans))
		(not (onLeftBank farmer)))
	)
)

